name: Tests

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Dependencies
        run: pnpm install -r
      - name: Test ${{ matrix.node-version }} ${{ matrix.platform }}
        run: npm run build
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: $\{{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
